### ISSUE TITLE
org.sparkle-project.Downloader crashing only while running in Xcode in os_unfair_lock

### ISSUE THREAD

**Issue by mikejurka** [tillhainbach/SwiftUISparkleTestApp#2]
Thanks for the great example project and documentation!

We have an app that uses some of this code, but running into this issue when running in Xcode:
https://github.com/sparkle-project/Sparkle/issues/1805

Any chance this you saw this issue as well?

**Comment by mikejurka** [comment]
ok, this was not an issue after i stopped using the downloader service.

**Comment by tillhainbach** [comment]
Hey, I recently pushed some updates to this example code base, which are not yet reflected in the README.md file. I added conformance to the `ObservableObject`Protocol, so that the CommandMenu can disabled the "update"-Button based on the `SPUUpdater.canCheckForUpdates` - property.
